# THIS CODE IS MY OWN WORK, IT WAS WRITTEN WITHOUT CONSULTING A TUTOR, CODE WRITTEN BY OTHER STUDENTS, OR CODE DERIVED FROM AN AI TOOL- Max Roberts


TARGET=myar
CC=gcc

.PHONY: cleanall cleanobj
all: $(TARGET)
myar: myar.o
cleanobj:
	$(RM) myar.o
cleanall: cleanobj
	$(RM) $(TARGET)
