# THIS CODE IS MY OWN WORK, IT WAS WRITTEN WITHOUT CONSULTING A TUTOR, CODE WRITTEN BY OTHER STUDENTS, OR CODE DERIVED FROM AN AI TOOL- Max Roberts
CC = gcc
CFLAGS = -Wall -g

pipesort: pipesort.c
	gcc $(CFLAGS) -o pipesort pipesort.c

clean:
	rm -f pipesort